#!/usr/bin/env bash
# install_pre_commit_hook.sh — .git/hooks/pre-commit shim を書き込む idempotent installer
#
# 設計書: docs/cmd020_scope_contamination_v2_incident_root_cause.md §4 (= L1+L2 階層解消)
#
# 目的:
#   本日 incident 3 件 (= 2026-05-13 ashigaru3/6/7 関連 commit) の真因は
#   `.git/hooks/pre-commit` 未 install (= `pre-commit install` framework 未起動)。
#   本 installer は framework 依存を排除し、bash + git のみで動作する shim を
#   .git/hooks/pre-commit に書き込む。SC + MC 両 WSL 環境で実行可。
#
# 動作:
#   1. REPO_ROOT を git rev-parse で取得 (= repo 外実行は exit 1)
#   2. .git/hooks/ 不在なら mkdir
#   3. shim 内容を heredoc で .git/hooks/pre-commit に書き出し (= 既存 file 上書き、idempotent)
#   4. chmod +x で実行権付与
#   5. 既装着の `pre-commit` framework が install されている場合、本 shim が framework hook を
#      無効化するため、--with-framework option で framework hook を後段呼出する shim を生成
#
# Invocation:
#   bash scripts/install_pre_commit_hook.sh                  # 標準 shim only
#   bash scripts/install_pre_commit_hook.sh --with-framework # framework hook 後段呼出 retain
#   bash scripts/install_pre_commit_hook.sh --dry-run        # 書込みせず予定内容を stdout
#
# Exit code:
#   0 = install 成功 (= idempotent overwrite 含む)
#   1 = repo 外 / disk error / permission
#
# SessionStart trigger proposal:
#   scripts/session_start_hook.sh から本 installer を呼出す改修案を別 cycle で起案。
#   CLAUDE.md Session Start 手順への記載は別 cycle で karo 経由起案。

set -euo pipefail

WITH_FRAMEWORK=0
DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --with-framework) WITH_FRAMEWORK=1 ;;
        --dry-run)        DRY_RUN=1 ;;
        *) echo "[install_pre_commit_hook] unknown arg: $arg" >&2; exit 1 ;;
    esac
done

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [ -z "$REPO_ROOT" ]; then
    echo "[install_pre_commit_hook] not inside git work tree" >&2
    exit 1
fi

HOOK_DIR="$REPO_ROOT/.git/hooks"
HOOK_PATH="$HOOK_DIR/pre-commit"

generate_shim() {
    cat <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by scripts/install_pre_commit_hook.sh (cmd_020 scope_contamination_v2)
# Do NOT edit manually; re-run the installer to regenerate.
#
# 目的: scope contamination 抑止 + author 整合 verify + secret 検出 + deliverable 整合 を
#       framework 依存なしで commit 直前に実行する。

set -uo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [ -z "$REPO_ROOT" ]; then
    exit 0
fi

STAGED_FILES=()
while IFS= read -r f; do
    [ -n "$f" ] && STAGED_FILES+=("$f")
done < <(git diff --cached --name-only --diff-filter=ACMRD 2>/dev/null || true)

if [ ${#STAGED_FILES[@]} -eq 0 ]; then
    exit 0
fi

run_step() {
    local name="$1" cmd="$2" pass_files="$3"
    if [ ! -f "$REPO_ROOT/$cmd" ]; then
        return 0
    fi
    if [ "$pass_files" = "yes" ]; then
        bash "$REPO_ROOT/$cmd" "${STAGED_FILES[@]}"
    else
        bash "$REPO_ROOT/$cmd"
    fi
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        echo "[pre-commit shim] $name exited $rc — commit aborted" >&2
        exit "$rc"
    fi
}

run_step "check_file_path_owner"     "scripts/lint/check_file_path_owner.sh"     no
run_step "pre_commit_author_verify"  "scripts/pre_commit_author_verify.sh"       no
run_step "check_secrets"             "scripts/lint/check_secrets.sh"             yes
run_step "check_deliverable_tracked" "scripts/lint/check_deliverable_tracked.sh" no
__FRAMEWORK_DELEGATION__

exit 0
SHIM
}

FRAMEWORK_BLOCK=""
if [ "$WITH_FRAMEWORK" -eq 1 ]; then
    FRAMEWORK_BLOCK=$'if command -v pre-commit >/dev/null 2>&1 && [ -f "$REPO_ROOT/.pre-commit-config.yaml" ]; then\n    pre-commit run --hook-stage pre-commit --files "${STAGED_FILES[@]}" || exit $?\nfi'
fi

CONTENT=$(generate_shim | awk -v fb="$FRAMEWORK_BLOCK" '{ gsub(/__FRAMEWORK_DELEGATION__/, fb); print }')

if [ "$DRY_RUN" -eq 1 ]; then
    echo "----- DRY RUN: would write to $HOOK_PATH -----"
    echo "$CONTENT"
    echo "----- END DRY RUN -----"
    exit 0
fi

mkdir -p "$HOOK_DIR"
echo "$CONTENT" > "$HOOK_PATH"
chmod +x "$HOOK_PATH"

echo "[install_pre_commit_hook] installed: $HOOK_PATH"
echo "[install_pre_commit_hook] with_framework=$WITH_FRAMEWORK"
echo "[install_pre_commit_hook] verify: bash $HOOK_PATH (= no-op on empty staged set)"
